### ISSUE TITLE
VM Host - 192.9.200.188 Memory issue

### ISSUE THREAD

**Issue by msrawat-isgec** [Isgec/ITIL-Server#15]
VM Host - 192.9.200.188 Memory issue

**Comment by msrawat-isgec** [comment]
Call log to HP and case detail is below.
@praveen-isgec 

Dear M S Rawat, 

Thank you for contacting Hewlett Packard Enterprise for your service needs. This email confirms that your request for service has been created as follows: 
Case Reference ID: 5353169558 
Status: Case is generated and in Progress 
Subject: HPE ProLiant DL380 Gen9 Server Models - Memory Issue
Product: HPE ProLiant DL380 Gen9 8SFF Configure-to-order Server 
Product number: 719064-B21 
Serial number: SGH805S6J6 
You will receive additional updates as work on your request proceeds. To follow or track the progress of your case online, please use the Hewlett Packard Enterprise Support Centre (HPESC) available from this link: //www.hpe.com/support/hpesc. 
Thank you again for contacting Hewlett Packard Enterprise Pointnext Services. 
Want to get faster resolution? Visit our Self-Solve Platforms! 
- Intuitive Support Portal built with Machine Learning Technology
@https://support.hpe.com 
- Get your Solution and Product Queries answered by our experts

**Comment by praveen-isgec** [comment]
If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

**Comment by praveen-isgec** [comment]
Dear Team,

 

Please update 

 

 

Regards

M.S.Rawat 

 

From: DCADMIN [mailto:dcadmin@isgec.co.in] 
Sent: Thursday, January 28, 2021 11:38 AM
To: 'ravi-sankar.chinna@hpe.com'
Cc: 'gsd_csc_case_mngmt@hpe.com'; 'esc-ap-isss-india@hpe.com'; 'gsd_csc_case_mngmt@hpe.com'
Subject: RE: LOG FILE REQUEST, PLEASE REPLY ALL: DO NOT EDIT THIS LINE<CASE:5353169558>

 

Hi

 

Password is not accept  and I have already uploaded the  logs in bleow ftp url

 

 

SFTP Access    : sftp -o Port=2222 e2742220@h3.ext.hpe.com
               : sftp -P 2222 e2742220@h3.ext.hpe.com
HTTPS Access   :  <https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fh3.ext.hpe.com%2fhprc&c=E,1,7bqQXx-Uvoqe0ojDbaYuZLlHU5f2xk2qN9pPdIj1WA8nKzcLFNfr4n1V4S7HwwOuDXEpuVsQ53jRY6Ih-YnJsgWsZGzKepf4TlK5bTIjbbwctQ3u&typo=1> https://h3.ext.hpe.com/hprc
Login          : e2742220
Password       : =DU4eb{L
OR
FTP Access     :  <https://linkprotect.cudasvc.com/url?a=ftp%3a%2f%2fe2742220%3a%3dDU4eb%7bL%40h3.ext.hpe.com&c=E,1,oXAwoUX5A3XT5HRsPn5bSKReJDzUsJjJSNZEiVin_3gsE3AfwLBDJisgAHgzG5LM2lb2mfxn5besIEa3xezhTqcCYBzO2bksSo_8ChxS&typo=1> ftp://e2742220:=DU4eb{L@h3.ext.hpe.com

 

 

Regards

M.S.Rawat 

 

From: ravi-sankar.chinna@hpe.com [mailto:ravi-sankar.chinna@hpe.com] 
Sent: Thursday, January 28, 2021 11:21 AM
To: dcadmin@isgec.co.in
Cc: ravi-sankar.chinna@hpe.com; gsd_csc_case_mngmt@hpe.com; esc-ap-isss-india@hpe.com; gsd_csc_case_mngmt@hpe.com
Subject: LOG FILE REQUEST, PLEASE REPLY ALL: DO NOT EDIT THIS LINE<CASE:5353169558>

 

Dear MSRawat,

This is an important email regarding your HPE support case 5353169558 (Serial# SGH805S6J6; Part# NA). 

In order to assist diagnosis we require some log files from you. The instructions on how to generate the logs are shown below together with the details of a temporary read/write dropbox to which you can upload them.

Once the logs have been uploaded, it is important that you reply to this email without changing the subject line and using the ""REPLY ALL"" feature. This will inform us that the logs are ready for analysis and diagnosis can continue.

Thank you for your co-operation.

SFTP Access    : sftp -o Port=2222 es169558@h3.ext.hpe.com
               : sftp -P 2222 es169558@h3.ext.hpe.com
HTTPS Access   :  <https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fh3.ext.hpe.com%2fhprc&c=E,1,pEYr3rLYUx0k6LW2H5QJGtwhRw9pd_KyvInHpGmf03T0WhZ3L9aK2VNhK_ujkXSq2t-gG7_-9ezWPr-kKzdrnDM96-stsI8E_3LbbU1G2jNJOsWk&typo=1> https://h3.ext.hpe.com/hprc
Login          : es169558
Password Reference Number: 15f03fbd-9455-4a65-b52e-2e6c812b1530

 

Please Note:
You will receive a separate email for password which will be mapped by "Password Reference Number" mentioned in this email.
DATA PRIVACY WARNING: CUSTOMER DATA PRIVACY ALERT
FILE ENCRYPTION AND SECURE TRANSPORT
It is the customer responsibility to ensure that their corporate and regulatory data privacy requirements are met.

Industry best practice is encrypting the file and securely sharing the key with the recipient as well as choosing a secure transport method (HTTPS or FTPS). 
Work with your HPE support resource for additional guidance on encryption and transmission options.


Here are the steps to generate logs:


Active Health System log




How to Generate Active Health System log via iLO GUI
1. Logon to HP iLO 4 GUI (IP address at POST visible or check server iLO Default Network Settings tag for DNS name).
2. Go to the menu on the left called: Active Health System Log.
3. Verify the date interval (Default is 7 days) and make sure that all possible failures are covered within this date range as selected.
4. Enter the possible Contact information so that the HPE Support agent can easily get back to user with follow up questions.
The Contact information text is the only readable text in this binary AHS log file.
5. Press the Download button to start downloading the AHS log file.


OR

Active Health System Log via Intelligent Provisioning (IP)
1. (Re-)Boot the server and press during boot at POST the F10 key on the keyboard.
The F10 icon at the bottom of the screen will light up now in white to confirm the F10 is pressed.
2. At the next screen select Perform Maintenance.
3. At Intelligent Provisioning Maintenance Screen select Active Health System download.
4. Verify at the next screen (Below) that users see the USB device connected. 
Either locally on the front/back side of the server or mounted via iLO as Virtual USB key. 
5. Verify the date interval (Default is 7 days) and make sure that all possible failures are covered within this date range as selected. 
6. Enter the possible Contact information so that the HPE Support agent can easily get back to user with follow up questions. 
The Contact information is the only readable text in this AHS log binary file. 
Hit the download button on the end to start saving the AHS log to the attached USB key.

OR

Generate an Active Health System log via AHSdownload for Windows Operating System:
1. Download AHSdownload utility from HPE FTP site to the HP ProLiant Gen8 Operating system. 
Click here to download AHSdownload utility HPE FTP site <https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fdownloads.hpe.com%2fpub%2fsoftlib2%2fsoftware1%2fpubsw-windows%2fp1783870791%2fv75797%2fAHSdownload_Windows_1.0.8.04.zip&c=E,1,_6OLsIW_gOZclqbBYa6pMM_7Y3pjSL0eouMlpMWx50CUeHNvwDwYTaKkYoD_xpw8o67jjEYzk0cVp_JcA2I7TVz_IWUpsw9iVsBZ4RpsoGivejE,&typo=1> . 
2. Extract the .zip file using WinZip or any other application. 
3. Verify the README.txt file for possible commandline options or just execute by typing: 
AHSdownload 


OR

Generate the Active Health System log via AHSdownload for LINUX distributions:
1. Download AHSdownload utility from HPE FTP site to the HP ProLiant Gen8 Operating system: 
Click here to download AHSdownload utility from HPE FTP site <https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fsupport.hpe.com%2fhpsc%2fswd%2fpublic%2fdetail%3fswItemId%3dMTX_368e697b23b049b48b13e7e84a&c=E,1,WCJibNNaQROZt6409DGtaDFygoUPKcwZ4xe862RcdyJFBRKNIX4Du97zgmbTuw7U70kKg-Y3dWnZBp7B_0t8hjSyjmbvy8xK_Cglbng0nS6HTgls6aj3XA,,&typo=1> . 
2. Extract the AHSdownload using for example: tar -xf {AHSdownload file name}.tar 
3. Verify the README.txt file for possible commandline options or just execute by typing: 
./AHSdownload 


OR 

Generating AHS using HPE Restful Interface Tool 
1] Download the HPE Restful Interface Tool from HPE Drivers and Software page 
2] Follow the commands as listed below to download and clear the AHS logs 
iLOrest > serverlogs –selectlog=AHS –u username –p password –url=XX.XX.XX



Should you require further assistance from HPE, please contact HPE Support.

Regards,
Ravi Sankar C, Hewlett Packard Enterprise Customer Solution Center.

**Comment by msrawat-isgec** [comment]
Dear Team, 

 

Please confirm When will be delivered the part along with engineer.

 

Regards

M.S.Rawat 

 

From: Value, Dispatch [mailto:value.dispatch@hpe.com] 
Sent: Thursday, January 28, 2021 3:13 PM
To: DCADMIN
Cc: Singh, Gyanender (HPE Pointnext, India Account Services)
Subject: RE: Case id : 5353169558 // ISGEC HEAVY ENGINEERING LIMITED

 

Hello Team

 

For the Subjected case id team is working on the case

 

Regards

Akram

 

From: DCADMIN [mailto:dcadmin@isgec.co.in] 
Sent: Thursday, January 28, 2021 2:08 PM
To: Value, Dispatch <value.dispatch@hpe.com>
Cc: Singh, Gyanender (HPE Pointnext, India Account Services)
<gyanender.singh@hpe.com>
Subject: RE: Case id : 5353169558 // ISGEC HEAVY ENGINEERING LIMITED

 

Hi Dhasharath

 

Right now I am available please call  me 9873805536, 8130295536

 

 

Regards

M.S.Rawat 

 

From: Value, Dispatch [mailto:value.dispatch@hpe.com] 
Sent: Thursday, January 28, 2021 1:17 PM
To: dcadmin@isgec.co.in
Cc: Singh, Gyanender (HPE Pointnext, India Account Services)
Subject: Case id : 5353169558 // ISGEC HEAVY ENGINEERING LIMITED

 

Hello Team,

 

This is with reference to above mentioned case id.

 

We are unable to reach you on the provided nos.(987) 380-5536

 

Request you to kindly provide us the below information to proceed further
with the scheduling. 

 

*Complete site address where the server is located.

*Contact details at site (name and number).

*GST No. of the organization. 

 

Also we would like to inform you that there would be delay in processing the
case. We will work with our internal teams and update you further on the
part shipment and engineer visit.

 

Thanks for your support

 

Regards,

Dhasharath

**Comment by msrawat-isgec** [comment]
Replaced Mother Board and One Memory Model Server is working fine.
@dhirendra-isgec  Dear sir cal has closer .

**Comment by dhirendra-isgec** [comment]
M
